### ISSUE TITLE
Bitmaps with negative height not decoded properly

### ISSUE THREAD

**Issue by Et999** [Twinside/Juicy.Pixels#105]
According to MSDN a bitmap with a negative height has the origin in upper-left corner (i.e. the image is upside down). Juicy pixels interprets the field as unsigned and instead creates a very large image.

Stackoverflow post that prompted the bug report (with example image)
http://stackoverflow.com/questions/32159800/juicy-pixels-complains-about-not-having-enough-memory

MSDN:
https://msdn.microsoft.com/en-us/library/windows/desktop/dd183376%28v=vs.85%29.aspx

**Comment by Twinside** [comment]
Thanks for the report, expect a bumped version on Hackage this afternoon

**Comment by Twinside** [comment]
Fixed in version 3.2.6.1
