### ISSUE TITLE
gif images are always encoded as GIF89a

### ISSUE THREAD

**Issue by gaa-cifasis** [Twinside/Juicy.Pixels#109]
I'm not sure if this is a bug. Is there a reason for that?

**Comment by Twinside** [comment]
It's simpler and valid to target the 89a version, enabling to share the same code for single images and animations. Writing a "Graphic Control Extension" mandate the use of this version, and as the block is optional, using this version is always valid.

**Comment by gaa-cifasis** [comment]
Uhm, i see. In any case, some utilities from giflib as well as others like gif2tiff expect always a GIF87a.

**Comment by Twinside** [comment]
I can still add a check for single image file, to put a 87a version

**Comment by gaa-cifasis** [comment]
Sure!, it will be nice to add another option for testing. Let me know if you need something..
