### ISSUE TITLE
Jpeg CMYK direct encoding

### ISSUE THREAD

**Issue by NCrashed** [Twinside/Juicy.Pixels#116]
Hi,

I work with Warcraft III BLP format that internally uses jpeg encoded in CMYK color space to store additional alpha layer. Decoding is fine, but JuicyPixels doesn't support writing CMYK jpeg directly without lossy conversion to YCbCr...

Is there any way to workaround that?

**Comment by Twinside** [comment]
So here goes the prototype, I'm not too sure about the current CMYK implementation as there is some fuzzy information about if the image needs to be inversed before encoding. I'd be happy to have some feedbacks on this point.
