### ISSUE TITLE
Vector constraint should be >= 0.10

### ISSUE THREAD

**Issue by lehins** [Twinside/Juicy.Pixels#127]
`NFData a => NFData (Vector a)` instance was not introduced until Vector package version 0.10, which causes JuicyPixels building to fail while using `vector-0.9.1` and lower.

Offending module is `Codec.Picture.Metadata.Exif` with lines 203-204:

    src/Codec/Picture/Metadata/Exif.hs:203:23:
        No instance for (NFData (V.Vector Word32))
          arising from a use of `rnf'
        Possible fix:
          add an instance declaration for (NFData (V.Vector Word32))
        In the first argument of `seq', namely `rnf l'
        In the expression: rnf l `seq` ()
        In an equation for `rnf': rnf (ExifLongs l) = rnf l `seq` ()

    src/Codec/Picture/Metadata/Exif.hs:204:24:
        No instance for (NFData (V.Vector Word16))
          arising from a use of `rnf'
        Possible fix:
          add an instance declaration for (NFData (V.Vector Word16))
        In the first argument of `seq', namely `rnf l'
        In the expression: rnf l `seq` ()
        In an equation for `rnf': rnf (ExifShorts l) = rnf l `seq` ()

**Comment by Twinside** [comment]
Thanks, let's see how Travis handles it.
