### ISSUE TITLE
Add Eq instance to `Image` data type

### ISSUE THREAD

**Issue by mrkkrp** [Twinside/Juicy.Pixels#129]
This may be useful in testing for example when you compare results of some processing/generation with expected results (maybe loaded from a file). Should be trivial to add, I can open a PR if you're OK with this proposition.

**Comment by Twinside** [comment]
Eh, why not!

**Comment by Twinside** [comment]
I think it's merged

**Comment by mrkkrp** [comment]
Took a while though ;-)
