### ISSUE TITLE
Why has TransparentPixel no setOpacity method?

### ISSUE THREAD

**Issue by leftaroundabout** [Twinside/Juicy.Pixels#132]
That class makes a lot of sense in that it FunDep-connects the RGBA-pixel variants with their respective RGB pendants. It would seem an obvious method for this class to have

    setTransparency :: PixelBaseComponent a -> b -> a

with e.g.

    setTransparency α (RGB8 r g b) = RGBA8 r g b α

is there a particular reason why this method isn't present?

**Comment by Twinside** [comment]
This typeclass was introduced while working on Rasterific, and I didn't need a setTransparency method for it. That's just it :]
