### ISSUE TITLE
GifDelay 1 creates animation as slow as GifDelay 10

### ISSUE THREAD

**Issue by AriPaaWun** [Twinside/Juicy.Pixels#137]
The delay in gif animation with `GifDelay` `1` is as slow as `GifDelay` `10` when using `writeGifAnimation`.
I have not tried creating an animation with other functions.

Here are some comparison gifs:
![delay_1](https://cloud.githubusercontent.com/assets/14271859/21644180/eb1698b6-d294-11e6-96eb-9ad0a196db5f.gif) Delay 1
![delay_10](https://cloud.githubusercontent.com/assets/14271859/21644178/eb14e386-d294-11e6-960e-dab2b0b0025c.gif) Delay 10
![delay_2](https://cloud.githubusercontent.com/assets/14271859/21644179/eb157e7c-d294-11e6-91b7-f5e89843603f.gif) Delay 2
![delay_5](https://cloud.githubusercontent.com/assets/14271859/21644177/eb1428ce-d294-11e6-8b9c-4c224c6aaca1.gif) Delay 5

Code to generate above gifs:
```
module Lib
    ( crunchInputToOutput,
      createDelayGifs
    ) where

import Codec.Picture (generateImage, writeGifAnimation)
import Codec.Picture.Gif (GifLooping(LoopingForever))
import Codec.Picture.Types (PixelRGB8(..), Image(..))

delayImages :: [Image PixelRGB8]
delayImages = [generateImage (\x y -> pixelMap [((1,1), True)] $ (x, y)) 5 3
              ,generateImage (\x y -> pixelMap [((1,1), True), ((2,1), True)] $ (x, y)) 5 3
              ,generateImage (\x y -> pixelMap [((1,1), True), ((2,1), True), ((3,1), True)] $ (x, y)) 5 3]
  where pixelMap pixels coord = case M.lookup coord (M.fromList pixels) of
                                    Just True -> PixelRGB8 255 0 0
                                    _         -> PixelRGB8 0 0 0

createDelayGif :: Int -> IO ()
createDelayGif delay = do
  let result = writeGifAnimation ("delay_" ++ show delay ++ ".gif") delay LoopingForever delayImages
  case result of
    Left msg -> putStrLn msg
    Right result -> do
      result
      putStrLn $ "Done " ++ show delay ++ "."

createDelayGifs :: IO ()
createDelayGifs = do
  createDelayGif 1
  createDelayGif 2
  createDelayGif 5
  createDelayGif 10
```

**Comment by Twinside** [comment]
Well, the data is written in the file, but I don't control the renderer, and there is some known timing difference between renderer/browser:

 * http://humpy77.deviantart.com/journal/Frame-Delay-Times-for-Animated-GIFs-214150546
 * http://webmasters.stackexchange.com/questions/26994/why-is-this-gifs-animation-speed-different-in-firefox-vs-ie

So it's not a Juicy.Pixel problem
