### ISSUE TITLE
Jpeg image fails to load with readImage

### ISSUE THREAD

**Issue by ruuda** [Twinside/Juicy.Pixels#142]
I am using `readImage` to load [this jpeg image](https://github.com/ruuda/blog/raw/be1bab82244ca1f9a01b909a9c158ca0ad062fe4/images/compressed/richys-groceries.jpg). This fails with the following error message:

    Cannot load file
    Jpeg Unknown JPG kind
    PNG Invalid PNG file, signature broken
    Bitmap Invalid Bitmap magic identifier
    GIF Invalid Gif signature : ÿØÿà

The file opens fine in Chromium, Firefox, and Eog. `file` and `identify` output:

    JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, extended sequential, precision 8, 1280x800, frames 3
    JPEG 1280x800 1280x800+0+0 8-bit sRGB 191436B 0.000u 0:00.000

JuicyPixels version: 3.2.8.2.

**Comment by Twinside** [comment]
Version [3.2.8.3](http://hackage.haskell.org/package/JuicyPixels-3.2.8.3) up on hackage with a fix for this ticket

**Comment by ruuda** [comment]
Thanks for the quick fix!
