### ISSUE TITLE
Shadowed Dependency Problem

### ISSUE THREAD

**Issue by WendyAnjanette** [Twinside/Juicy.Pixels#143]
I'm trying to install JuicyPixels with this command `cabal install JuicyPixels` but I'm having this problem: 
Building library for JuicyPixels-3.2.8.3..
<command line>: cannot satisfy -package-id vector-0.12.0.1-6mmeV84KOvJADXavl6mOiY:
    vector-0.12.0.1-6mmeV84KOvJADXavl6mOiY is unusable due to shadowed dependencies:
      primitive-0.6.2.0-V0ibjLQDdN6fcQS5bjLVg
    (use -v for more information)

I'm stuck I'm a beginner in this and I don't have idea how to fix this. Please help.

**Comment by Twinside** [comment]
I would advise to use the [stack](https://docs.haskellstack.org/en/stable/README/) tool as a beginner to avoid the dependency/ghc version problems or try to use cabal's sandbox.

These kind of problems are more ghc/cabal related than JuicyPixels.

**Comment by lehins** [comment]
@WendyAnjanette Looks like you are hitting this issue with Cabal: https://github.com/haskell/cabal/issues/4728
