### ISSUE TITLE
Support round-trip of Exif data.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [Twinside/Juicy.Pixels#145]
It's currently not possible to use JuicyPixels to modify a jpeg image.

The reason for this is that essential Exif data will be lost, such as orientation.

The `TODO` related to writing Exif data should be fixed.  I *think* https://github.com/Twinside/Juicy.Pixels/blob/8b67ffa61245fa21646dc7d3cdb58688a4960c2c/src/Codec/Picture/Jpg/Types.hs#L435 is the area that needs improving.

**Comment by alexanderkjeldaas** [comment]
@Twinside Since you have a donation link, I'll donate EUR 50 to get this issue fixed.  Requirement is only that Orientation is round-tripped on the test-image in my PR.

**Comment by Twinside** [comment]
It was a bit more complex than expected, some tools being more inclusive in what they parse (exif tools, Juicy.Pixels itself) while other being stricter (windows property import, XnView). Orientation was round-tripped on the first commit, but I made it work for flash/illumination also (and any other Exif tags not including the GPS ones).

**Comment by Twinside** [comment]
Released on hackage as version 3.2.9

**Comment by alexanderkjeldaas** [comment]
Cool!  I'm testing this on my side..

**Comment by alexanderkjeldaas** [comment]
lgtm

**Comment by Twinside** [comment]
Thanks for the donation :)
