### ISSUE TITLE
Building fails with GHC 7.8.4

### ISSUE THREAD

**Issue by mrkkrp** [Twinside/Juicy.Pixels#146]
I have a project that depends on JuicyPixels, and recently Travis CI with GHC 7.8.4 started to fail because JuicyPixels doesn't build anymore. Here is the log:

https://travis-ci.org/mrkkrp/identicon/jobs/306724560#L698

Version of the library Cabal tried to build is `JuicyPixels-3.2.9.1`, which I recon is the latest version.

I'd like to note that previously (probably with older versions of JuicyPixels) the build succeeded.

**Comment by Twinside** [comment]
I'd merge a pull request for it, but I wont bother for a compiler version that's nearly 3 years old.

**Comment by mrkkrp** [comment]
If you don't bother supporting this version of GHC, reflect it in the cabal file.

Do you actually run CI on this project? I don't see any badge and no `.travis.yml` file in the root.

**Comment by phadej** [comment]
@Twinside if you don't bother with GHC-7.8.4, please adjust the `base` lower bound.

I made revisions for broken releases on Hackage.
- https://hackage.haskell.org/package/JuicyPixels-3.2.9/revisions/
- https://hackage.haskell.org/package/JuicyPixels-3.2.9.1/revisions/
