### ISSUE TITLE
Please use at least 3rd digit bumps when introducing new features

### ISSUE THREAD

**Issue by phadej** [Twinside/Juicy.Pixels#147]
In the changelog for 3.2.9.1 is written:

>  * Feature: Paletted alpha png saving

And the diff seems to move some functions into newly introduced type-class: http://hdiff.luite.com/cgit/JuicyPixels/diff?id=3.2.9.1&id2=3.2.9

As a new name is exported, the version should been bumped to `3.2.10`. [PVP](https://pvp.haskell.org/) says

> **Non-breaking change**. Otherwise, if only new bindings, types, classes, non-orphan instances or modules (but see below) were added to the interface, then *A.B* **MAY** remain the same but the new *C* **MUST** be greater than the old *C*.

There is also a practical aspect to this, `MIN_VERSION_JuicyPixels` macros can distinguish only 3 first digits of the version (because 4th shouldn't ever matter).

**Comment by Twinside** [comment]
ok
