### ISSUE TITLE
Odd distortion of a certain JPEG image

### ISSUE THREAD

**Issue by mtolly** [Twinside/Juicy.Pixels#148]
Just happened to notice this weird square pattern on a specific input image. I'm not familiar enough with JPEG to know if there's a certain feature of the encoding that's not supported. The input seems to show correctly in all other tools I've tried though.

Input:

![cover](https://user-images.githubusercontent.com/1427698/34328555-117f294a-e8a7-11e7-90b8-b920d1c20328.jpg)

In case GitHub reencoded here is the original: http://www.gameost.info/wp-content/uploads/2016/09/gitadora-tri-boost-original-soundtrack-volume-02.jpg

Output:

![out](https://user-images.githubusercontent.com/1427698/34328556-15436992-e8a7-11e7-998f-175a6c730e7d.png)

Converted with `readImage "in.jpg" >>= \(Right dimg) -> writePng  "out.png" $ convertRGB8 dimg` using 871e18b3d284bf9562523d9b51f2aab457e23684 (and also saw the same result on I think 3.2.8.3 from Hackage).

**Comment by Twinside** [comment]
I'll look into it asap

**Comment by Twinside** [comment]
Fix released as version 3.2.9.2
