### ISSUE TITLE
Source code for JuicyPixels-3.2.9.2 contains invalid UTF-8 byte sequence

### ISSUE THREAD

**Issue by peti** [Twinside/Juicy.Pixels#149]
The haddock phase for JuicyPixels-3.2.9.2 fails with the following error:

~~~~
Running hscolour for JuicyPixels-3.2.9.2...
Preprocessing library for JuicyPixels-3.2.9.2..
HsColour: src/Codec/Picture/Jpg/Progressive.hs: hGetContents: invalid argument (invalid byte sequence)
~~~~

**Comment by Twinside** [comment]
Looks like it's not fixed by previous release :/

**Comment by juhp** [comment]
I just ran into this...

Is it just the one char after `=`?

**Comment by juhp** [comment]
https://gist.github.com/jeffreycwitt/89d6a9137c312e1b4b35472cd19a7d40
It is caused by: `naïvely` ;)
UTF-8 is your friend :-)
