### ISSUE TITLE
Uniform quantization of GIF images is broken

### ISSUE THREAD

**Issue by william42** [Twinside/Juicy.Pixels#152]
The following code:
```haskell
module Main where

import Codec.Picture
import Codec.Picture.Gif
import Codec.Picture.ColorQuant

imagePal :: (Image Pixel8,Palette)
imagePal = uniformize $ generateImage renderer 256 256
  where renderer x y = PixelRGB8 (fromIntegral x) (fromIntegral y) 128

gradientPaletteOptions = PaletteOptions
  { paletteCreationMethod = Uniform,
    enableImageDithering = False,
    paletteColorCount = 256 }

uniformize = palettize gradientPaletteOptions



main :: IO ()
main = case writeGifImageWithPalette "grad.gif" im pal of
         Left err -> putStrLn err
         Right action -> action >> putStrLn "done!"
    where (im,pal) = imagePal
```

should produce a rather simplistic gradient.  Instead, it produces [this incorrect grid](https://covering.space/scraps/badgradient.gif).  My examination of the source code suggests that the quantization you're doing is using a slightly wrong binary operation, with some `255-dr` and such that should be `256-dr` so that the bitmask actually clears off the lower bits.

**Comment by Twinside** [comment]
I'll upload the fixed version to hackage during next week

**Comment by william42** [comment]
Cool.  Inform me when you do.

**Comment by william42** [comment]
https://covering.space/scraps/goodgradient.gif

**Comment by Twinside** [comment]
Up on hackage
