### ISSUE TITLE
Bug on alpha channel removal?

### ISSUE THREAD

**Issue by alexandrelucchesi** [Twinside/Juicy.Pixels#155]
I'm getting strange results trying to convert an `RGBA8` to `RGB`.

Here's my code:

```haskell
main :: IO ()
main = do
    Right rgba <- readImage "lion-rgba.png"
    let rgb = convertRGB8 rgba
    writePng "lion-rgb.png" rgb
```
And the images used.

(1) Input image ("lion-rgba.png"):

![lion-rgba](https://user-images.githubusercontent.com/2234780/39901839-544ba60c-54a1-11e8-93c8-c059ca87b7b3.png)

(2) Resulting image ("lion-rgb.png"):
![lion-rgb](https://user-images.githubusercontent.com/2234780/39901838-53f52ffc-54a1-11e8-82f9-a166ea8b05e1.png)

Is this a problem with Juicy.Pixels, my code or the image? 😅

**Comment by Twinside** [comment]
well convertRGB8 just strip out the alpha layer, the color value behind transparent can be anything, in that case: an extruded lion. To get what you want you should maybe special case and perform a proper alpha blending against a background of your choice (There is no helper in the library for that).
