### ISSUE TITLE
Loosen bounds on bytestring

### ISSUE THREAD

**Issue by vmchale** [Twinside/Juicy.Pixels#196]
Hi,

Now that `bytestring` is at [0.11.0.0](http://hackage.haskell.org/package/bytestring), the bound could be loosened to include it. This works on my computer and would help in my [webp](https://hub.darcs.net/vmchale/webp) project.

Thanks :)

**Comment by amigalemming** [comment]
Now `bytestring` 0.12 is available and should be supported.
