### ISSUE TITLE
Distortion (and possibly segfault) in decoding a certain JPEG

### ISSUE THREAD

**Issue by mtolly** [Twinside/Juicy.Pixels#205]
Tracking down a segfault in my app led me to the decoding of a specific JPEG, which I think may be invoking out of bounds or uninitialized memory access.

![test](https://user-images.githubusercontent.com/1427698/157176198-7c6e645d-23f2-4d13-913d-b14f05fbbae2.jpg)

(I don't think GitHub reencoded this, but I can upload it elsewhere if needed)

Doing a simple decode/encode with 3.3.6, I get:

![test](https://user-images.githubusercontent.com/1427698/157176263-5ddf3908-25f2-4055-a60f-5e30d432a65f.png)

I wasn't able to get a demo program to crash at all (which just does the decode/encode), and my own app only crashes some of the time, possibly dependent on the memory layout beforehand. So I'm not 100% sure that the decoding is causing the segfault, but it seems plausible based on the half-gibberish decoded result.

**Comment by Twinside** [comment]
Ok, the jpeg format is a bit unusual, there is two vertical macroblock stacked, hence the proper rendering of half the lines of macro block

**Comment by mtolly** [comment]
Thank you for such a quick fix! Crash seems to be resolved completely 😄
