### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by byorgey** [Twinside/Juicy.Pixels#224]
When trying to build `diagrams-lib` on GHC 9.10, compilation of `JuicyPixels-3.3.8` fails with the error:
```
src/Codec/Picture/Metadata.hs:231:13: error: [GHC-87543]
    Ambiguous occurrence ‘foldl'’.
    It could refer to
       either ‘Prelude.foldl'’,
              imported from ‘Prelude’ at src/Codec/Picture/Metadata.hs:14:8-29
              (and originally defined in ‘ghc-internal-9.1001.0:GHC.Internal.Data.Foldable’),
           or ‘Codec.Picture.Metadata.foldl'’,
              defined at src/Codec/Picture/Metadata.hs:227:1.
    |
231 | foldMap f = foldl' (\acc v -> acc `mappend` f v) mempty
    |             ^^^^^^
```
However, this seems to have already been addressed by https://github.com/Twinside/Juicy.Pixels/commit/b3f1c16d4e77393198938294e952aa14b4f9e9b9 (I am able to successfully build `JuicyPixels` HEAD with GHC 9.10), but there has been no release including this change.  Could you upload the latest version of JuicyPixels to Hackage, please?

**Comment by Twinside** [comment]
Hi, can you tell me if the release branch of the repository is even building? I don't have the haskell tooling around anymore, and it looks things have changed too much for a quick and dirty. If good I'll push asap

**Comment by byorgey** [comment]
@Twinside I was able to successfully build the `release` branch locally with both `ghc-9.8.2` and `ghc-9.10.1`.

**Comment by Twinside** [comment]
Ok I'll upload
