### ISSUE TITLE
createMutableImage could be more performant

### ISSUE THREAD

**Issue by nomeata** [Twinside/Juicy.Pixels#82]
I was about to embark on a profiling-and-optimization session for my code, only to discover that most of the time is spent in `createMutableImage`:

```
         createMutableImage                   Codec.Picture.Types                 2540           1   32.0   28.3    89.6   95.7
          createMutableImage.\                Codec.Picture.Types                 2544    23040000    0.0    0.0     0.0    0.0
          unsafeWritePixel                    Codec.Picture.Types                 2543    23040000   57.6   67.4    57.6   67.4
          componentCount                      Codec.Picture.Types                 2542           1    0.0    0.0     0.0    0.0
```
I would have expected `createMutableImage` to an efficient methods to fill the array, but as  `createMutableImage` is implemented via `generateImage` this does not seem to be the case. Could this be improved?

**Comment by dagit** [comment]
It looks like the time is spent in `unsafeWritePixel` which just calls `unsafeWrite`. Unless you could batch the writes, how will you make that faster? I see that createMutableImage is not `INLINE` or `SPECIALIZE`, but I don't think that is creating an issue here.

It would be interesting to manually insert an SCC where `f` is called in the body of `generateImage`. Maybe there is a lot of work being done at that point that is misattributed to `unsafeWritePixel`?

**Comment by Twinside** [comment]
I have the [PackeablePixel](http://hackage.haskell.org/package/JuicyPixels-3.2.2/docs/Codec-Picture-Types.html#t:PackeablePixel) machinery for this kind of use. I added these while optimising Rasterific. The downside is not all pixel types are handled, those not fitting in a Word32 or Word64 are discarded.

The idea of PackedPixel is to cast the pixel to an atomic type containing all the pixel information and then to call one write or one vector fill on it. It helps tremendously, but doesn't handle RGB8 color space sadly and I'm not sure this kind of trick could handle endianness issues.

I can try to sparkle some `INLINE` pragma, or depending on your needs provide a `createUninitializedMutableImage`

**Comment by nomeata** [comment]
> It looks like the time is spent in unsafeWritePixel which just calls unsafeWrite. Unless you could 
> batch the writes, how will you make that faster? I see that createMutableImage is not INLINE or
> SPECIALIZE, but I don't think that is creating an issue here.

`unsafeWritePixel` also does the index manipulation, right?

Also,the call to `unsafeWritePixel`  itself is expensive, as it is overloaded.

I could imagine adding a `unsafeFillPixel` command that simply fills the whole vector with the pixel would speed it up a lot, as then the loop is entirely in monomorphic code, and the index calculation will be a simple loop.

**Comment by nomeata** [comment]
> I have the PackeablePixel machinery for this kind of use. I added these while optimising Rasterific.
> The downside is not all pixel types are handled, those not fitting in a Word32 or Word64 are discarded.

This looks useful, not sure why I overlooked it. But how do I get my `MutableImage` in the first place? Looks like `createUninitializedMutableImage` might be required, or alternatively a `fastCreateMutableImage` with a `PackedPixel` constraint.

**Comment by Twinside** [comment]
Here comes `newMutableImage`, fast filling can already be done using `fillImageWith`
