### ISSUE TITLE
Fails to read RGB JPEGs

### ISSUE THREAD

**Issue by sdroege** [Twinside/Juicy.Pixels#85]
![test](https://cloud.githubusercontent.com/assets/301846/6349225/ee9c56e6-bc30-11e4-9d96-bdeffe64f318.jpg)

The attached JPEG fails to be read currently, resulting in the descriptive error "Prelude.(!!): index too large" :smile: I assume this is because RGB is not supported yet in the JPEG loading code.

Other than supporting RGB, it would also be good to catch this error earlier with something more descriptive

**Comment by Twinside** [comment]
I fixed the crash, it decode the image, but take it as YCbCr instead of RGB. I will fix this problem tonight.

**Comment by sdroege** [comment]
Great, thanks :)
