### ISSUE TITLE
sRGB format is not recognized

### ISSUE THREAD

**Issue by phaazon** [Twinside/Juicy.Pixels#86]
I have an image, uploaded [here](http://phaazon.net/pub/monday_again.png) that is in sRGB. You can try it out by yourself with `identify -format '%[colorspace]' the.png`.

However, JuicyPixels sees that as **YCbCr8**, which is wrong. Furthermore, I thought that converting that back to RGB was okay using the regular formula for JPG to RGB encoding, but it doesn’t work…

**Comment by Twinside** [comment]
The image is well decoded for me...

I've passed it through the test suite and obtain a visually correct image.

**Comment by phaazon** [comment]
Yeah, that’s nasty, I should have removed the .png extension ahah. The latest version. `identify` is from `ImageMagick`. It’s a tool that gives info on an image. What “test suite” are you talking about? Just try what I did: `readImage`, pattern match on the `DynamicImage` result… ;)

**Comment by Twinside** [comment]
~~~~{haskell}
import Codec.Picture
import Codec.Picture.Types

main :: IO ()
main = do
  rawBytes <- readImage "monday_again.png"
  case rawBytes of
    Right (ImageYCbCr8 img) ->
      writePng "out.ycbcr8.png" $ (convertImage img :: Image PixelRGB8)
    Left err -> putStrLn err
    Right _ -> putStrLn "Unrecognized color space"
~~~~
Maybe ImageMagick assume the content of the image will be converted back to RGB by the underlying decoding library, which is a choice I didn't make. In any case, the file is encoded in YCbCr8.

**Comment by phaazon** [comment]
I also use `convertImage` to use that, but I’m not so sure it’s in YCbCr8. ImageMagick says it’s sRGB, as GIMP also says.

**Comment by phaazon** [comment]
I testes with several other .png, and they’re all in RGB8. I guess it was an exception. Thanks for the quick reply though :) .
