### ISSUE TITLE
Bride to the Friday lib for in-Haskell image manipulation

### ISSUE THREAD

**Issue by cies** [Twinside/Juicy.Pixels#89]
It seems to exist for Gloss and Repa already; but a bridge to Friday would also be really nice.

JuicyPixels and Fiday together would provide a very attractive all-in-Haskell solution for the basic image processing needs of most web applications.

I also raised this [issue on the Friday side of the bride](https://github.com/RaphaelJ/friday/issues/12)

**Comment by cies** [comment]
A preliminary implementation of this bridge now exists.

https://github.com/TomMD/friday-juicypixels

Please close.

**Comment by Twinside** [comment]
Ok, thanks
