### ISSUE TITLE
Specify (recommended) DPI

### ISSUE THREAD

**Issue by bergey** [Twinside/Juicy.Pixels#93]
in formats that support this.  This feature [was recently requested on pandoc-discuss](https://groups.google.com/forum/#!searchin/pandoc-discuss/juicypixels/pandoc-discuss/Tpaa5QMwD2Y/ynsYgLrHhgYJ).  I think discussion on Diagrams lists has been inconclusive as to whether we want to support physical units, but having the option wouldn't hurt.

**Comment by Twinside** [comment]
And it's more or less needed for Rasterific also, I'll have a look after it.

**Comment by Twinside** [comment]
Done and released with JuicyPixels v3.2.5
